config/routes.rb
Rails.application.routes.draw do
  root to: 'application#home'
  get '/login', to: 'sessions#new'
  get '/signup', to: 'users#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  post '/signup', to: 'users#create'
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :destinations, only: [:index, :new, :create] do
    resources :itineraries do
      delete :destroy_all, on: :collection
    end
  end

  resources :itineraries, only: [:show, :update]

  
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :itinerary        
    
    validates :time, :description, presence: true

    scope :order_activities, -> (itinerary) {where(itinerary_id: itinerary.id).order(:time)}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
    has_many :itineraries, dependent: :destroy
    has_many :users, through: :itineraries

    accepts_nested_attributes_for :itineraries

    validates :city, :country, presence: true
    validate :destination_entered_is_unique

    def destination_entered_is_unique
        if Destination.find_by(city: city, state: state, country: country)
            errors.add(:city, "already exists. Please select from drop down menu.")
        end
    end

    def full_destination_name
        "#{city.split.map(&:capitalize).join(' ')}, #{state.split.map(&:capitalize).join(' ') if state}#{"," if state.present?} #{country.split.map(&:capitalize).join(' ')}"
    end

    scope :popular_trips, -> {joins(:itineraries).group('id').order('count(destinations.id) desc').limit(3)}
    scope :alphabetize_destinations, -> {order(:city)}
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
    belongs_to :user
    belongs_to :destination
    has_many :activities, dependent: :destroy

    accepts_nested_attributes_for :activities,
        allow_destroy: true,
        reject_if: proc {|act| act['time'].blank? && act['description'].blank?}



    validates :date, presence: true

    scope :trips_itineraries, -> (user, destination) {where(destination_id: destination, user_id: user.id)}
    scope :order_itineraries, -> {order(:date)}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :itineraries
  has_many :destinations, through: :itineraries

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6 }
  validate :is_email?

  def is_email?
    if !email.match(/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i)
      errors.add(:email, "not a valid email")
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper

    def home
        redirect_if_logged_in
    end

    private

    def find_destination
        @destination = Destination.find_by(id: params[:destination_id])
    end

    def redirect_if_logged_in
        if logged_in?
            redirect_to destinations_path
        end
    end

    def not_logged_in?
        if !logged_in?
            redirect_to root_path
        end
    end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
    before_action :not_logged_in?, only: [:index, :new]
    before_action :destination_collection_select, only: [:new, :create]
    
    def index
        @destinations = current_user.destinations.uniq.sort_by { |d| d.city}
    end

    def new
        @top_destinations = Destination.popular_trips
        @destination = Destination.new
    end
    
    def create
        @destination = Destination.find_by(id: destination_params[:id])
        if @destination
            redirect_to destination_itineraries_path(@destination)
        else
            @destination = Destination.new(destination_params)
            if @destination.save
                redirect_to destination_itineraries_path(@destination)
            else
                render :new
            end
        end
    end

    private

    def destination_params
        params.require(:destination).permit(:city, :state, :country, :id)
    end

    def destination_collection_select
        @destinations = Destination.alphabetize_destinations
    end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
    before_action :find_destination, only: [:new, :index, :create]
    before_action :find_itinerary, only: [:show, :edit, :update, :destroy]
    before_action :not_logged_in?, only: [:index, :show, :new, :edit]
    
    def index
        @itineraries = Itinerary.trips_itineraries(current_user, @destination).order_itineraries
    end


    def show
        @activities = Activity.order_activities(@itinerary)
    end
   
    def new
        @itinerary = @destination.itineraries.build
        activities_build
    end

    def create
        @itinerary = @destination.itineraries.build(itinerary_params)
        @itinerary.user_id = session[:user_id]
        if @itinerary.save
            redirect_to destination_itinerary_path(@destination, @itinerary)
        else
            render :new
        end
    end

    def edit
        activities_build
    end

    def update
        @itinerary.update(itinerary_params)
        if @itinerary.save
            redirect_to destination_itineraries_path(@itinerary.destination, @itinerary)
        else
            render :edit
        end        
    end

    def destroy
        @itinerary.destroy 
        redirect_to destination_itineraries_path(@itinerary.destination)
    end

    def destroy_all
        itineraries = Itinerary.trips_itineraries(current_user, params[:destination_id])
        itineraries.destroy_all
        redirect_to destinations_path
    end

    private

    def itinerary_params
        params.require(:itinerary).permit(:date, :destination_id, :user_id, activities_attributes: [:id, :time, :description, :_destroy])
    end

    def find_itinerary
        @itinerary = Itinerary.find_by(id: params[:id])
    end

    def activities_build
        8.times {@itinerary.activities.build}
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new #login form
    redirect_if_logged_in
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to destinations_path
    else
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to login_path
  end

  def omniauth
    user = User.find_or_create_by(uid: request.env['omniauth.auth'][:uid], provider: request.env['omniauth.auth'][:provider]) do |u|
      u.first_name = request.env['omniauth.auth'][:info][:first_name]
      u.last_name = request.env['omniauth.auth'][:info][:last_name]
      u.email = request.env['omniauth.auth'][:info][:email]
      u.password = SecureRandom.hex(15)
    end
    if user.valid?
      session[:user_id] = user.id
      redirect_to destinations_path
    else
      redirect_to login_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        redirect_if_logged_in
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to destinations_path
        else
            render :new
        end
    end

    private

    def user_params
        params.permit(:first_name, :last_name, :email, :password)
    end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        current_user
    end

    def display_date(itinerary)
        itinerary.date.strftime("%A, %b %e, %Y")
    end

    def display_time(activity)
        activity.time.strftime("%l:%M %p")
    end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<h1>Tripper<h1>

<br>

<h4>Prepare for your trips!</h4>

<br><br>

<h5><%= link_to "Login", login_path %> |
<%= link_to "Signup", signup_path %></h5>

app/views/destinations/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/destinations/index.html.erb
<h2>Your Trips</h2>

<% @destinations.each do |destination| %>
    <li><%= link_to destination.full_destination_name, destination_itineraries_path(destination) %>
<% end %>
<br>

<br><%= link_to "Create New Destination", new_destination_path %>

app/views/destinations/new.html.erb
<% if @top_destinations %>
<h2>Top Destinations</h2><br>
  <% @top_destinations.each do |destination| %>
    <li><%= destination.city %>
  <% end %>
<% end %>

<br><br>

<h1>Plan A New Trip</h1><br>

<%= render partial: "errors", locals: {object: @destination} %><br>

<%= form_with model: @destination do |f| %>
    <h4>Select your destination:</h4>
    <%= f.collection_select :id, @destinations, :id, :full_destination_name, include_blank: true %><br><br>
    <h4>Enter a destination</h4>
    <%= f.label :city %>
    <%= f.text_field :city %> <br><br>
    <%= f.label :state %>
    <%= f.text_field :state %> <br><br>
    <%= f.label :country %>
    <%= f.text_field :country %> <br><br>
    <%= f.submit 'Submit' %>
<% end %>
<br>
<%= link_to "Go Back", destinations_path %>

app/views/itineraries/_form.html.erb
<br><br>
<h2>Activities</h2><br>
<%= f.fields_for :activities do |a| %>
    <%= a.label :time %>
    <%= a.time_field :time %>
    <%= a.label :description %>
    <%= a.text_field :description %>
    <% if a.object.persisted? %>
      <%= a.check_box :_destroy %>
      <%= a.label :_destroy, "Remove" %>
    <% end %>
    <br><br>
    
<% end %>

app/views/itineraries/edit.html.erb
<h2>Update <%= display_date(@itinerary) %>'s Itinerary</h2>

<%= render partial: "destinations/errors", locals: {object: @itinerary} %>

<%= form_with model: @itinerary do |f| %>

    <%= render partial: "form", locals: {f: f} %>

    <%= f.submit 'Submit' %>

<% end %>
<br>
<%= link_to "Go Back", destination_itinerary_path(@itinerary.destination, @itinerary) %>

app/views/itineraries/index.html.erb
<h1> <%= @destination.city %> Trip</h1>

<br>

<% @itineraries.each do |itinerary| %>
    <%= link_to display_date(itinerary), destination_itinerary_path(@destination, itinerary) %>
        <% itinerary.activities.sort_by{|act| act.time}.each do |activity| %>
        <li><%= display_time(activity) %>
        <%= activity.description %></li>
    <% end %><br>
<% end %>


<%= link_to "Create New Itinerary", new_destination_itinerary_path %> |
<%= link_to "Delete This Trip", destroy_all_destination_itineraries_path(@destination), method: :delete, data: {confirm: 'Are you sure?'} %>

app/views/itineraries/new.html.erb
<h1> Create an Itinerary for Your Trip</h1><br>

<%= render partial: "destinations/errors", locals: {object: @itinerary} %>

<%= form_with model: [@destination, @itinerary] do |f| %>
    <%= f.hidden_field :destination_id, value: @destination.id %>
    <%= f.label :date %>
    <%= f.date_field :date %>
    
    <%= render partial: "form", locals: {f: f} %>

    <%= f.submit 'Submit' %>
<% end %>
<br>
<%= link_to "Go Back", destination_itineraries_path(@destination) %>

app/views/itineraries/show.html.erb
<h4><%= display_date(@itinerary) %> in <%= @itinerary.destination.city %></h4>

<% @activities.each do |act| %>
    <li><%= display_time(act) %>
    <%= act.description %></li>
<% end %>
<br>


<%= link_to "Go Back to All #{@itinerary.destination.city} Itineraries", destination_itineraries_path(@itinerary.destination) %> |
<%= link_to "Edit This Itinerary", edit_destination_itinerary_path(@itinerary.destination, @itinerary) %> |
<%= link_to "Delete This Itinerary", {action: :destroy, id: @itinerary.id}, method: :delete, data: {confirm: 'Are you sure?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTravelApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br><br>
    <% if logged_in? %>
      <%= link_to "All Destinations", destinations_path %> |
      <%= link_to "Logout", logout_path, method: :post, data: {confirm: 'Are you sure?'} %>
      <br><br>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/_google_oauth.html.erb
<br>
<h3> Or Login with Google:</h3>
<br>
<%= button_to "Google", '/auth/google_oauth2' %>

app/views/users/new.html.erb
<h1>Create an Account</h1>

<br><br>

<%= render partial: "destinations/errors", locals: {object: @user} %>

<%= form_with url: signup_path do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %> <br><br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %> <br><br>
    <%= render partial: "sessions/form", locals: {f: f} %>
    <%= f.submit 'Create Account' %>
<% end %>

<%= render partial: "google_oauth" %>
<br>
<%= link_to "Already have an account? Login Here!", login_path %>